cleantalk.settings:
  type: mapping
  label: Settings
  mapping:
    cleantalk_authkey:
      type: string
    cleantalk_check_comments:
      type: integer
    cleantalk_check_comments_automod:
      type: integer 
    cleantalk_check_comments_min_approved:
      type: integer 
    cleantalk_check_register:
      type: integer 
    cleantalk_check_webforms:
      type: integer   
    cleantalk_check_contact_forms:
      type: integer 
    cleantalk_check_forum_topics:
      type: integer                              
    cleantalk_check_ccf:
      type: integer
    cleantalk_link:
      type: integer
    cleantalk_sfw:
      type: integer          
